project:
  name: FraudDetect
  version: 1.0.0

seed: 42

schema:
  version: v2

logging:
  level: DEBUG
  format: "%(asctime)s - %(name)s - %(levelname)s - %(message)s"
  save_logs: true 
  log_dir: logs

features:
  drop_cols:
    - step
    - nameOrig
    - nameDest
    - isFlaggedFraud
  cat_cols:
    - type
  num_cols:
    - amount
    - oldbalanceOrg
    - newbalanceOrig
    - newbalanceDest
    - oldbalanceDest
    - errorBalanceOrig
    - errorBalanceDest
  target_column_name: isFraud

training:
  test_size: 0.2
  cross_validation: 3
  stratify: true

model:
  name: xgboost
  parameters:
    n_estimators: 263
    max_depth: 11
    learning_rate: 0.08155447589149051
    subsample: 0.5564405658710594
    colsample_bytree: 0.5639188659465246
    scale_pos_weight: 7.452034376962025
    objective: binary:logistic
    eval_metric : logloss
    tree_method: hist
    device: cuda
    predictor: gpu_predictor
    n_jobs: 1


metrics:
  precision_limit: 0.65
  model_picker_metric: pr_auc

mlflow:
  mlflow_tracking_uri: https://dagshub.com/aryanshah2109/FraudDetect.mlflow  
  experiment_name: Main_Experiment

inference:
  best_model_path: models/best_model.pkl
  best_metrics_path: models/best_metrics.json
  best_preprocessor_path: models/best_preprocessor.pkl

  